name: Go CI

on:
  push:
    branches: 
     - main
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: go mod tidy

    - name: Lint code
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.39.0
        golangci-lint run

    - name: Run tests
      run: go test ./...

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/go_app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/go_app:latest

    # - name: Deploy to staging
    #   run: |
    #       IMAGE_TAG=${{ env.IMAGE_TAG }}
    #       ssh user@staging-server 'docker pull ${{ secrets.DOCKER_USERNAME }}/go-app:${IMAGE_TAG} && docker service update --image ${{ secrets.DOCKER_USERNAME }}/go-app:${IMAGE_TAG} go-app-service'
